@file:OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class)

package com.mob8n.ui

import android.content.Context
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.AutoAwesome
import androidx.compose.material.icons.rounded.Settings
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.AssistChip
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SuggestionChipDefaults
import androidx.compose.material3.SuggestionChip
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.LiveRegionMode
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.liveRegion
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.mob8n.ai.AiPrefs
import com.mob8n.ai.Builder
import com.mob8n.ai.S1Prefs
import com.mob8n.ai.NanoStatus
import com.mob8n.core.Catalog
import com.mob8n.core.Graph
import com.mob8n.core.Workflow
import com.mob8n.engine.Engine
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch
import java.util.UUID

private val SUGGESTIONS = listOf(
    "When I share a link, summarise it with AI and notify me",
    "Every weekday at 8:00 read my calendar and speak the plan",
    "When Instagram posts a notification, save it to a note",
)
private val REFINE_EXAMPLES = listOf("Add a notification on error", "Use Spotify instead of YouTube", "Run only on weekdays")

const val NANO_CANNOT_BUILD = "Build with AI needs a cloud provider — Gemini Nano's 256-token output cannot hold a workflow. Pick a Default AI in Settings > AI"

/** What blocks Generate right now, or null. Mirrors Llm.defaultTarget's chain closely enough for the pre-flight message; Builder is the authority. */
internal fun buildBlocker(defaultProvider: String?, anyKey: Boolean, nano: NanoStatus, preferOnDevice: Boolean): String? = when {
    defaultProvider == AI_NANO -> NANO_CANNOT_BUILD
    defaultProvider != null -> null
    !anyKey && nano == NanoStatus.AVAILABLE -> NANO_CANNOT_BUILD
    !anyKey -> "Connect an AI provider first"
    preferOnDevice && nano == NanoStatus.AVAILABLE -> NANO_CANNOT_BUILD
    else -> null
}

private fun progressText(p: Builder.Progress?, label: String) = when (p) {
    Builder.Progress.Asking, null -> "Asking $label…"
    Builder.Progress.Validating -> "Checking the workflow…"
    Builder.Progress.Repairing -> "Repairing…"
}

/** Builder.Result -> unsaved draft workflow (DESIGN2 §6.5): laid out, disabled, parked in Drafts until the editor saves it. */
internal fun draftFrom(name: String, graph: Graph): Workflow =
    Workflow(id = UUID.randomUUID().toString(), name = "$name (Generated by AI)", enabled = false, graph = autoLayout(graph), updatedAt = System.currentTimeMillis())

/**
 * Build with AI (DESIGN2 §6.6). `workflowId` = opened from that editor: the description is then applied as a change to that
 * workflow's current graph and the result still opens as a NEW draft (the original is untouched; Refine edits in place instead).
 */
@Composable
fun BuildWithAiScreen(workflowId: String?, engine: Engine, catalog: Catalog, onBack: () -> Unit, onOpen: (Screen) -> Unit) {
    val ctx = LocalContext.current
    val scope = rememberCoroutineScope()
    LaunchedEffect(Unit) { AiPrefs.load(ctx) }
    val providers by AiPrefs.providers.collectAsStateWithLifecycle()
    val defaultAi by AiPrefs.defaultAi.collectAsStateWithLifecycle()
    val defaultLabel by AiPrefs.defaultLabel.collectAsStateWithLifecycle()
    val nano by AiPrefs.nanoStatus.collectAsStateWithLifecycle()
    val preferOnDevice by AiPrefs.preferOnDevice.collectAsStateWithLifecycle()
    val blocker = buildBlocker(defaultAi?.provider, providers.values.any { it.hasKey }, nano, preferOnDevice)
    val providerLabel = defaultAi?.let { AiPrefs.providerLabel(it.provider) } ?: "the AI"

    var description by rememberSaveable(workflowId) { mutableStateOf("") }
    var job by remember { mutableStateOf<Job?>(null) }
    var progress by remember { mutableStateOf<Builder.Progress?>(null) }
    var error by remember { mutableStateOf<String?>(null) }
    var base by remember(workflowId) { mutableStateOf<Workflow?>(null) }
    LaunchedEffect(workflowId) { base = workflowId?.let { id -> runCatching { engine.workflow(id) }.getOrNull() ?: Drafts.map[id] } }
    val running = progress != null   // observable (Job.isActive is not a Compose state)

    fun generate() {
        error = null; progress = Builder.Progress.Asking
        job = scope.launch {
            try {
                val cur = base
                val r = Builder.build(ctx, catalog, description = if (cur == null) description.trim() else "", current = cur?.graph, currentName = cur?.name,
                    instruction = if (cur == null) null else description.trim(), onProgress = { progress = it }, decisionEngine = S1Prefs.isConfigured(ctx))
                val wf = draftFrom(r.name, r.graph)
                Drafts.map[wf.id] = wf
                onOpen(Screen.Editor(wf.id))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                error = e.message ?: e.javaClass.simpleName
            } finally { progress = null }
        }
    }

    Scaffold(topBar = { MahoutTopBar("Build with AI", onBack = onBack) }) { pad ->
        Column(Modifier.fillMaxSize().padding(pad).verticalScroll(rememberScrollState()).padding(horizontal = pageGutter(), vertical = Space.l), verticalArrangement = Arrangement.spacedBy(Space.m)) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text("Default AI", style = MaterialTheme.typography.labelLarge, modifier = Modifier.weight(1f))
                AssistChip(onClick = { onOpen(Screen.AiSettings) }, label = { Text(defaultLabel) }, leadingIcon = { Icon(Icons.Rounded.AutoAwesome, contentDescription = null) },
                    modifier = Modifier.semantics { contentDescription = "Default AI: $defaultLabel. Open AI settings" })
            }
            if (blocker != null) SectionCard(tone = Tone.Danger) {
                Column(verticalArrangement = Arrangement.spacedBy(Space.s)) {
                    Text(blocker, style = MaterialTheme.typography.bodyMedium)
                    PillButton("AI settings", onClick = { onOpen(Screen.AiSettings) }, icon = Icons.Rounded.Settings, tone = Tone.Neutral, contentDescription = "Open AI settings")
                }
            }
            base?.let { Text("Based on \"${it.name}\": describe the change; the result opens as a new draft.", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant) }
            OutlinedTextField(
                value = description, onValueChange = { description = it }, minLines = 4, label = { Text(if (base == null) "Describe the workflow" else "Describe the change") }, enabled = !running,
                modifier = Modifier.fillMaxWidth().semantics { contentDescription = "Workflow description" },
            )
            if (base == null) FlowRow(horizontalArrangement = Arrangement.spacedBy(6.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                for (s in SUGGESTIONS) SuggestionChip(onClick = { description = s }, label = { Text(s, style = MaterialTheme.typography.labelMedium) }, enabled = !running,
                    shape = RoundedCornerShape(Radius.s), icon = { Icon(Icons.Rounded.AutoAwesome, contentDescription = null, modifier = Modifier.size(SuggestionChipDefaults.IconSize)) },
                    modifier = Modifier.semantics { contentDescription = "Use suggestion: $s" })
            }
            if (running) {
                LinearProgressIndicator(Modifier.fillMaxWidth())
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text(progressText(progress, providerLabel), style = MaterialTheme.typography.bodyMedium, modifier = Modifier.weight(1f).semantics { liveRegion = LiveRegionMode.Polite })
                    TextButton(onClick = { job?.cancel(); job = null }, modifier = Modifier.heightIn(min = 48.dp).semantics { contentDescription = "Cancel generation" }) { Text("Cancel") }
                }
            } else {
                PillButton("Generate", onClick = ::generate, modifier = Modifier.fillMaxWidth(), icon = Icons.Rounded.AutoAwesome, enabled = description.isNotBlank() && blocker == null, contentDescription = "Generate workflow")
            }
            error?.let { e ->
                SectionCard(tone = Tone.Danger) {
                    Column(verticalArrangement = Arrangement.spacedBy(Space.s)) {
                        Text(e, style = MaterialTheme.typography.bodyMedium, modifier = Modifier.semantics { liveRegion = LiveRegionMode.Polite })
                        Row {
                            Spacer(Modifier.weight(1f))
                            TextButton(onClick = ::generate, enabled = description.isNotBlank() && blocker == null, modifier = Modifier.semantics { contentDescription = "Retry generation" }) { Text("Retry") }
                        }
                    }
                }
            }
            Text("The result opens unsaved in the editor for review; nothing runs until you save and enable it.", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
    }
}

/**
 * Refine with AI (DESIGN2 §6.6): one instruction over the current canvas graph. `onResult` receives the validated (or best-effort)
 * graph plus remaining validator lines; the caller swaps the canvas and offers Undo.
 */
@Composable
fun RefineWithAiDialog(catalog: Catalog, graph: Graph, name: String, onDismiss: () -> Unit, onResult: (Graph, List<String>) -> Unit) {
    val ctx: Context = LocalContext.current
    val scope = rememberCoroutineScope()
    val defaultAi by AiPrefs.defaultAi.collectAsStateWithLifecycle()
    val providerLabel = defaultAi?.let { AiPrefs.providerLabel(it.provider) } ?: "the AI"
    var instruction by rememberSaveable { mutableStateOf("") }
    var job by remember { mutableStateOf<Job?>(null) }
    var progress by remember { mutableStateOf<Builder.Progress?>(null) }
    var error by remember { mutableStateOf<String?>(null) }
    val running = progress != null   // observable (Job.isActive is not a Compose state)

    fun run() {
        error = null; progress = Builder.Progress.Asking
        job = scope.launch {
            try {
                val r = Builder.build(ctx, catalog, description = "", current = graph, currentName = name, instruction = instruction.trim(), onProgress = { progress = it }, decisionEngine = S1Prefs.isConfigured(ctx))
                onResult(r.graph, r.errors)
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                error = e.message ?: e.javaClass.simpleName
            } finally { progress = null }
        }
    }

    AlertDialog(
        onDismissRequest = { if (!running) onDismiss() },
        title = { Text("Refine with AI") },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedTextField(instruction, { instruction = it }, minLines = 2, label = { Text("What should change?") }, enabled = !running,
                    modifier = Modifier.fillMaxWidth().semantics { contentDescription = "Refine instruction" })
                FlowRow(horizontalArrangement = Arrangement.spacedBy(6.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                    for (s in REFINE_EXAMPLES) SuggestionChip(onClick = { instruction = s }, label = { Text(s, style = MaterialTheme.typography.labelMedium) }, enabled = !running, modifier = Modifier.semantics { contentDescription = "Use example: $s" })
                }
                if (running) {
                    LinearProgressIndicator(Modifier.fillMaxWidth())
                    Text(progressText(progress, providerLabel), style = MaterialTheme.typography.bodySmall, modifier = Modifier.semantics { liveRegion = LiveRegionMode.Polite })
                }
                error?.let { Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall, modifier = Modifier.semantics { liveRegion = LiveRegionMode.Polite }) }
            }
        },
        confirmButton = {
            if (running) TextButton(onClick = { job?.cancel(); job = null }, modifier = Modifier.semantics { contentDescription = "Cancel refine" }) { Text("Cancel") }
            else TextButton(onClick = ::run, enabled = instruction.isNotBlank(), modifier = Modifier.semantics { contentDescription = if (error == null) "Refine" else "Retry refine" }) { Text(if (error == null) "Refine" else "Retry") }
        },
        dismissButton = { if (!running) TextButton(onClick = onDismiss, modifier = Modifier.semantics { contentDescription = "Close refine dialog" }) { Text("Close") } },
    )
}
